name: ctacrime
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - scipy
  - altair
  - pydeck
  - streamlit >= 1.12.0
  - seaborn
  - matplotlib
  - vl-convert-python
  - ipython